import type {
  SystemInformation,
  SystemSummary,
} from "src/types/system-information";

export const systemSummaryFixture: SystemSummary = {
  osName: "Windows",
  osVersion: "11",
  osLongVersion: "Windows 11 Pro",
  architecture: "x86_64",
  hostName: "private-host",
  cpuModel: "Example CPU",
  logicalCoreCount: 16,
  totalMemoryBytes: 17_179_869_184,
  collectedAt: "2026-07-28T10:00:00.000Z",
  warnings: [],
};

export const systemInformationFixture: SystemInformation = {
  summary: systemSummaryFixture,
  system: {
    platform: "windows",
    osName: "Windows",
    osVersion: "11",
    osLongVersion: "Windows 11 Pro",
    kernelVersion: "10.0.26100",
    architecture: "x86_64",
    hostName: "private-host",
    uptimeSeconds: 93_840,
  },
  cpu: {
    model: "Example CPU",
    vendor: "Example Vendor",
    physicalCoreCount: 8,
    logicalCoreCount: 16,
    frequencyMhz: 4200,
    usagePercent: 24.5,
  },
  memory: {
    totalBytes: 17_179_869_184,
    usedBytes: 6_871_947_674,
    availableBytes: 10_307_921_510,
    usagePercent: 40,
    swapTotalBytes: 4_294_967_296,
    swapUsedBytes: 1_073_741_824,
    swapUsagePercent: 25,
  },
  gpus: [
    {
      name: "Integrated Example",
      vendorId: 1,
      deviceId: 2,
      deviceType: "integrated",
      backend: "dx12",
      driver: "private-driver",
      driverInfo: "private-driver-details",
      dedicatedMemoryBytes: null,
      sharedMemoryBytes: null,
    },
    {
      name: "Discrete Example",
      vendorId: 3,
      deviceId: 4,
      deviceType: "discrete",
      backend: "vulkan",
      driver: null,
      driverInfo: null,
      dedicatedMemoryBytes: null,
      sharedMemoryBytes: null,
    },
  ],
  disks: [
    {
      name: "System",
      fileSystem: "NTFS",
      mountPoint: "C:\\private",
      kind: "ssd",
      removable: false,
      totalBytes: 1_099_511_627_776,
      availableBytes: 549_755_813_888,
      usedBytes: 549_755_813_888,
      usagePercent: 50,
    },
  ],
  runtime: {
    appName: "zx-manager",
    appVersion: "0.1.0",
    tauriVersion: "2.11.3",
    targetTriple: "x86_64-pc-windows-msvc",
    webviewVersion: "140.0.0",
  },
  availability: {
    cpuUsage: true,
    memory: true,
    swap: true,
    disks: true,
    gpuBasic: true,
    gpuMemory: false,
    runtimeTarget: true,
    webviewVersion: true,
  },
  collectedAt: "2026-07-28T10:00:00.000Z",
  warnings: [],
};
