const enUS = {
  common: {
    app: { name: "Local Console", description: "Infrastructure Manager" },
    actions: { add: "Add", cancel: "Cancel", close: "Close", confirm: "Confirm", more: "More actions", refresh: "Refresh", save: "Save", search: "Search" },
    status: { error: "Error", failed: "Failed", healthy: "Healthy", loading: "Loading", success: "Success", warning: "Warning" },
  },
  navigation: {
    groups: { management: "Management", resources: "Resources" },
    items: { certificates: "Certificates", configuration: "Configuration", dashboard: "Dashboard", help: "Help", logs: "Logs", networkPorts: "Network Ports", nginx: "Nginx", search: "Search", services: "Services", settings: "Settings", systemMonitor: "System Monitor" },
    quickActions: { addService: "Add Service", createProxy: "Create Proxy", importCertificate: "Import Certificate", installNginx: "Install Nginx", openConfiguration: "Open Configuration" },
    labels: { localActions: "Local actions", notifications: "Notifications", openMachineActions: "Open machine actions", quickAction: "Quick Action" },
    machine: { name: "Local Machine", platform: "Windows 11 · x64", openGuide: "Open guide", restartApp: "Restart app", systemInfo: "System info" },
    toast: { futureAction: "This action is ready for a future Tauri command.", moduleMock: "This module is represented by a local dashboard mock.", selected: "{{label}} selected" },
  },
  dashboard: {
    title: "Dashboard", subtitle: "Monitor and manage local infrastructure services · {{updated}}", updatedJustNow: "Updated just now", updatedSecondsAgo: "Updated a few seconds ago",
    systemHealthy: "System Healthy", systemStatus: "System status", refreshing: "Refreshing", refreshSuccessTitle: "Dashboard refreshed", refreshSuccessDescription: "Local service and resource snapshots are up to date.",
    cards: { nginx: { title: "Nginx Status", value: "Running", description: "Nginx 1.26.2 is running", detail: "Listening on ports 80 and 443" }, cpu: { title: "CPU Usage", description: "Normal system load", detail: "8 cores · 2.4 GHz average" }, memory: { title: "Memory Usage", description: "6.4 GB of 16 GB used", detail: "9.6 GB available" }, services: { title: "Active Services", description: "12 of 15 services running", detail: "3 services stopped or need attention" } },
    headerActions: { dashboardSettings: "Dashboard settings", exportDiagnostics: "Export diagnostics", openActions: "Open dashboard actions", openSystemReport: "Open system report", mockDescription: "This dashboard action is currently running in mock mode." },
    chart: { title: "System Resource Usage", description: "CPU and memory usage during the selected period", cpu: "CPU Usage", memory: "Memory Usage", range: { "24h": "Last 24 hours", "7d": "Last 7 days", "30d": "Last 30 days" }, rangeLabel: "Resource chart time range" },
    tabs: { services: "Services", events: "Recent Events", changes: "Configuration Changes", health: "Health Checks", views: "Service management views" },
    columns: { actions: "Actions", cpu: "CPU", memory: "Memory", port: "Port", status: "Status", type: "Type", version: "Version" },
    columnSettings: { customize: "Customize Columns", visible: "Visible columns" },
    activity: { changes: "Configuration changes", events: "Recent events", health: "Health checks", status: { info: "Info", success: "Success", warning: "Warning" }, timestamps: { attention: "Attention required", fiveMinutes: "5 minutes ago", fortyTwoMinutes: "42 minutes ago", oneHour: "1 hour ago", eighteenMinutes: "18 minutes ago", threeHours: "3 hours ago", today1422: "Today, 14:22", yesterday: "Yesterday", yesterday1008: "Yesterday, 10:08", jul251840: "Jul 25, 18:40", twoMinutes: "2 minutes ago", healthy: "Healthy" }, titles: { nginxReloaded: "Nginx configuration reloaded", redisThreshold: "Redis memory threshold reached", nodeRestarted: "Node API restarted", certificateScan: "Certificate scan completed", postgresBackup: "PostgreSQL backup created", portReleased: "Port 8080 released", resourceCheck: "System resource check", proxyAdded: "Proxy route added", localGateway: "Local gateway", certificateValidity: "Certificate validity" }, descriptions: { nginxReloaded: "Configuration validation completed successfully.", redisThreshold: "Memory usage exceeded the configured 70% threshold.", nodeRestarted: "Development process restarted after a file change.", certificateScan: "One certificate requires attention.", postgresBackup: "Local snapshot stored successfully.", portReleased: "The previous development process exited normally.", resourceCheck: "CPU and memory levels are within normal limits.", proxyAdded: "Added /api route for the local Node service.", configNginx: "Updated gzip and cache-control directives.", configPostgres: "Raised max_connections from 100 to 150.", configEnv: "Updated the internal API base URL.", localGateway: "HTTP, TLS, and upstream checks passed in 43 ms.", certificateValidity: "One certificate expires within the next 14 days." } },
  },
  services: {
    table: { actionsFor: "Open actions for {{name}}", select: "Select {{name}}", selectAll: "Select all services", service: "Service" },
    status: { error: "Error", running: "Running", stopped: "Stopped", warning: "Warning" }, startupModes: { automatic: "Automatic", disabled: "Disabled", manual: "Manual" }, types: { application: "Application", cache: "Cache", database: "Database", nginx: "Nginx", node: "Node", system: "System" },
    actions: { editConfiguration: "Edit Configuration", openLogs: "Open Logs", remove: "Remove Service", restart: "Restart", start: "Start", stop: "Stop" },
    dialog: { add: "Add Service", title: "Add local service", description: "Register a local executable for management. No system command will be executed.", serviceName: "Service Name", serviceType: "Service Type", executablePath: "Executable Path", workingDirectory: "Working Directory", startupMode: "Startup Mode", port: "Port", selectServiceType: "Select a service type", selectStartupMode: "Select a startup mode", optional: "Optional" },
    confirmation: { removeTitle: "Remove service?", stopTitle: "Stop service?", removeDescription: "{{name}} will be removed from this local dashboard. This does not delete its files.", stopDescription: "{{name}} will stop accepting local traffic until it is started again." },
    toast: { added: "{{name}} added", addedDescription: "The service is registered locally in a stopped state.", localAction: "{{name}} is ready for a future Tauri integration.", operationError: "Unable to {{operation}} {{name}}", operationSuccess: "{{name}} {{operation}}", operationSuccessDescription: "The dashboard mock state was updated successfully.", removed: "{{name}} removed", removedDescription: "Only the local dashboard entry was removed.", operations: { restart: "restarted", start: "started", stop: "stopped" } },
    descriptions: { nginx: "Local reverse proxy and static file server", postgresql: "Primary local development database", redis: "Cache and background queue storage", nodeApi: "Internal REST API development process", localWebApp: "Vite frontend preview server", certificateWatcher: "Monitors local TLS certificate expiration", dockerEngine: "Local container runtime and image service", rabbitmq: "Local message broker for integration testing", minio: "S3-compatible local object storage", prometheus: "Metrics collection and query service", grafana: "Local dashboards and metrics exploration", mailpit: "Local email capture and inspection", sshAgent: "Manages local development credentials", backgroundWorker: "Processes queued development jobs", fileSync: "Synchronizes shared local project assets", custom: "{{startupMode}} service · {{path}}" },
  },
  settings: { title: "Settings", appearance: { title: "Appearance", theme: "Theme", light: "Light", dark: "Dark", system: "System", systemResolvedLight: "System (currently light)", systemResolvedDark: "System (currently dark)" }, language: { title: "Language", label: "Interface language", zhCN: "简体中文", enUS: "English" }, storageDescription: "Language and theme preferences are stored locally.", toast: { languageChanged: "Language changed to {{language}}", themeChanged: "Theme changed to {{theme}}" }, labels: { changeLanguage: "Change interface language", changeTheme: "Change theme" } },
  validation: { executablePathRequired: "Enter an executable path.", invalidPort: "Enter an integer port between 1 and 65535.", serviceNameRequired: "Enter a service name.", serviceTypeRequired: "Select a service type.", startupModeRequired: "Select a startup mode.", workingDirectoryRequired: "Enter a working directory." },
} as const;

export default enUS;
